<?php
declare(strict_types=1); require __DIR__.'/config.php'; require_once __DIR__.'/bricklink_pov.php'; ensure_dirs();
$a=$_GET['action']??'';
$currentUser = $a==='status' ? require_role([ROLE_OWNER]) : require_login();
$pdo=db();
function lval(PDO $pdo,string $id){$s=$pdo->prepare("SELECT * FROM valuations WHERE unit_id=? ORDER BY observed_at DESC,rowid DESC LIMIT 1");$s->execute([$id]);return $s->fetch()?:null;}
function price_unit(PDO $pdo,string $id):void{$v=lval($pdo,$id);if(!$v)return;$s=$pdo->prepare("SELECT * FROM inventory_units WHERE unit_id=?");$s->execute([$id]);$u=$s->fetch();if(!$u)return;$m=null;if(in_array($u['sealed_status'],['sealed','unknown'],true)&&$v['whole_new']!==null)$m=(float)$v['whole_new'];elseif($v['whole_used']!==null)$m=(float)$v['whole_used'];elseif($v['whole_new']!==null)$m=(float)$v['whole_new'];if(!$m)return;$pv=$v['part_out_sold']!==null?(float)$v['part_out_sold']:null;$r=($pv&&$m>0)?$pv/$m:null;$pr=0;if($r!==null){if($r>=3)$pr=.25;elseif($r>=2.5)$pr=.20;elseif($r>=2)$pr=.15;elseif($r>=1.5)$pr=.09;elseif($r>=1.2)$pr=.04;} $ca=0;if(in_array($u['box_condition'],['worn','damaged'],true))$ca=$u['box_condition']==='damaged'?-.06:-.03;if($u['condition_state']==='damaged')$ca-=.08;$rf=fn($n)=>max(1,round($n/5)*5);$e=['Whole-set reference: $'.number_format($m,2),$r!==null?'Sold-based POV ratio: '.number_format($r,2).'x':'POV unavailable: neutral support','POV ask support: +'.round($pr*100).'%','Condition adjustment: '.round($ca*100).'%','Marketplace negotiation buffer included in ask.'];$pdo->prepare("INSERT INTO pricing_recommendations(pricing_id,unit_id,valuation_id,calculated_at,market_reference,pov_ratio,ask_price,target_price,minimum_price,strategy,explanation_json) VALUES(?,?,?,?,?,?,?,?,?,?,?)")->execute([uuidv4(),$id,$v['valuation_id'],now_iso(),$m,$r,$rf($m*(1.06+$pr+$ca)),$rf($m*(.96+$pr*.55+$ca)),$rf($m*(.86+$pr*.30+$ca)),'sell_complete',json_encode($e)]);}
if($a==='status'){ $c=['pending'=>0,'fetching'=>0,'retry'=>0,'complete'=>0,'failed'=>0];foreach($pdo->query("SELECT status,COUNT(*) c FROM pov_queue GROUP BY status") as $r)$c[$r['status']]=(int)$r['c'];$rec=$pdo->query("SELECT set_num,checked_at,sold_average,current_average FROM pov_cache ORDER BY checked_at DESC LIMIT 8")->fetchAll();json_response(['ok'=>true,'counts'=>$c,'recent'=>$rec,'interval_seconds'=>POV_REQUEST_INTERVAL_SECONDS]);}
if($a==='queue_all'){ $force=!empty($_POST['force']);$sets=$pdo->query("SELECT DISTINCT catalog_set_num FROM inventory_units WHERE catalog_set_num IS NOT NULL AND status IN ('available','listed','reserved')")->fetchAll(PDO::FETCH_COLUMN);$q=0;$fresh=0;foreach($sets as $set){$r=queue_pov_for_set($pdo,$set,$force);$r['queued']?$q++:$fresh++;}json_response(['ok'=>true,'unique_sets'=>count($sets),'queued'=>$q,'fresh_cache'=>$fresh]);}
if($a==='process_next'){ $job=$pdo->query("SELECT * FROM pov_queue WHERE status IN ('pending','retry') AND (next_attempt_at IS NULL OR next_attempt_at<='".now_iso()."') ORDER BY COALESCE(next_attempt_at,created_at),created_at LIMIT 1")->fetch(); if(!$job)json_response(['ok'=>true,'processed'=>false]);$pdo->prepare("UPDATE pov_queue SET status='fetching',attempts=attempts+1,updated_at=? WHERE queue_id=?")->execute([now_iso(),$job['queue_id']]);try{$p=fetch_bricklink_pov($job['set_num'],'N');$pdo->beginTransaction();$pdo->prepare("INSERT INTO pov_cache(set_num,condition_code,sold_average,current_average,checked_at,source_url,last_error) VALUES(?,?,?,?,?,?,NULL) ON CONFLICT(set_num) DO UPDATE SET condition_code=excluded.condition_code,sold_average=excluded.sold_average,current_average=excluded.current_average,checked_at=excluded.checked_at,source_url=excluded.source_url,last_error=NULL")->execute([$job['set_num'],'N',$p['soldAverage'],$p['currentAverage'],$p['checkedAt'],$p['sourceUrl']]);$u=$pdo->prepare("SELECT unit_id FROM inventory_units WHERE catalog_set_num=? AND status IN ('available','listed','reserved')");$u->execute([$job['set_num']]);$units=$u->fetchAll(PDO::FETCH_COLUMN);foreach($units as $id){$o=lval($pdo,$id);$pdo->prepare("INSERT INTO valuations(valuation_id,unit_id,observed_at,currency,source_label,msrp,whole_new,whole_used,part_out_sold,part_out_for_sale,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)")->execute([uuidv4(),$id,now_iso(),$o['currency']??'USD',trim(($o['source_label']??'').(($o&&$o['source_label'])?' + ':'').'BrickLink POV'),$o['msrp']??null,$o['whole_new']??null,$o['whole_used']??null,$p['soldAverage'],$p['currentAverage'],'Automatic POV enrichment']);price_unit($pdo,$id);} $pdo->prepare("UPDATE pov_queue SET status='complete',updated_at=?,next_attempt_at=NULL,last_error=NULL WHERE queue_id=?")->execute([now_iso(),$job['queue_id']]);$pdo->commit();json_response(['ok'=>true,'processed'=>true,'set_num'=>$job['set_num'],'units_updated'=>count($units),'sold_average'=>$p['soldAverage'],'current_average'=>$p['currentAverage']]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$att=(int)$job['attempts']+1;$fail=$att>=POV_MAX_RETRIES;$next=$fail?null:(new DateTimeImmutable('now'))->modify('+'.min(60,5*$att).' minutes')->format(DateTimeInterface::ATOM);$pdo->prepare("UPDATE pov_queue SET status=?,attempts=?,updated_at=?,next_attempt_at=?,last_error=? WHERE queue_id=?")->execute([$fail?'failed':'retry',$att,now_iso(),$next,$e->getMessage(),$job['queue_id']]);json_response(['ok'=>false,'error'=>$e->getMessage(),'will_retry'=>!$fail],502);}}
json_response(['ok'=>false,'error'=>'Unknown action'],404);
